services:
  - type: web
    name: 850minddata-bot
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: python telegram_bot.py

    envVars:
      - key: BOT_TOKEN
        sync: false
